AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Create resources for a project that transcribes church sermons and indexes
  text as embeddings into OpenSearch serverless
Parameters:
  AppName:
    Default: llm-apps-blog
    Type: String
    AllowedValues: [ llm-apps-blog ]
    Description: Name of the overall application, this is used while creating the ML model endpoint.
  OpenSearchIndexName:
    Default: llm_apps_embeddings
    Type: String
    Description: Name of the OpenSearch index for storing embeddings.
Resources:
  # Storage for the original media file, configured to send notifications to the EventBridge
  TranscribeMediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub bucket-${AWS::AccountId}-${AWS::Region}-church-sermons-media
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  # media bucket is configured to allow necessary access to the Transcribe and Step Functions services
  TranscribeMediaBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Statement:
          - Sid: TranscribeMediaReadPolicy
            Effect: Allow
            Principal:
              Service: 'transcribe.amazonaws.com'
            Action:
              - s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref TranscribeMediaBucket
                - /*
          - Sid: TranscribeMediaReadPolicy
            Effect: Allow
            Principal:
              Service: 'states.amazonaws.com'
            Action:
              - s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref TranscribeMediaBucket
                - /*
          - Sid: HttpsOnly
            Action: s3:*
            Effect: Deny
            Principal: "*"
            Resource:
              - !Join [ '',[ 'arn:aws:s3:::',!Ref TranscribeMediaBucket,'/*' ] ]
              - !Join [ '',[ 'arn:aws:s3:::',!Ref TranscribeMediaBucket ] ]
            Condition:
              Bool:
                aws:SecureTransport: false
      Bucket: !Ref TranscribeMediaBucket

  # Storage for the Transcribe job results
  TranscribeResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub bucket-${AWS::AccountId}-${AWS::Region}-church-sermons-results
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  TranscribeResultsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: TranscribeMediaWritePolicy
            Effect: Allow
            Principal:
              Service: 'transcribe.amazonaws.com'
            Action:
              - s3:PutObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref TranscribeResultsBucket
                - /*
          - Sid: HttpsOnly
            Action: s3:*
            Effect: Deny
            Principal: "*"
            Resource:
              - !Join ['',['arn:aws:s3:::',!Ref TranscribeResultsBucket,'/*']]
              - !Join ['',['arn:aws:s3:::',!Ref TranscribeResultsBucket]]
            Condition:
              Bool:
                aws:SecureTransport: false

      Bucket: !Ref TranscribeResultsBucket

# Step Function to invoke Transcribe with an Event Bridge rule to trigger the execution when an upload is detected to the media bucket
  ChurchSermonsTranscribeStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Tracing:
        Enabled: true
      Events:
        S3MediaTrigger:
          Type: EventBridgeRule
          Properties:
            EventBusName: default
            Pattern:
              source:
                - aws.s3
              detail-type:
                - "Object Created"
              detail:
                bucket:
                  name:
                    - !Ref TranscribeMediaBucket
      Definition:
        Comment: Invoke Transcribe on a media file, when complete execute the results query Step Function and output the results
        StartAt: StartTranscriptionJob
        TimeoutSeconds: 900
        States:
          StartTranscriptionJob:
            Type: Task
            Comment: Start a transcribe job on the provided media file
            Parameters:
              Media:
                MediaFileUri.$: States.Format('s3://{}/{}', $.detail.bucket.name, $.detail.object.key)
              TranscriptionJobName.$: "$.detail.object.key"
              IdentifyLanguage: true
              OutputBucketName: !Ref TranscribeResultsBucket
            Resource: !Sub 'arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:aws-sdk:transcribe:startTranscriptionJob'
            Next: Wait
          Wait:
            Type: Wait
            Seconds: 60
            Next: GetTranscriptionJob
          GetTranscriptionJob:
            Type: Task
            Comment: Retrieve the status of an Amazon Transcribe job
            Parameters:
              TranscriptionJobName.$: "$.TranscriptionJob.TranscriptionJobName"
            Resource: !Sub 'arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:aws-sdk:transcribe:getTranscriptionJob'
            Next: TranscriptionJobStatus
          TranscriptionJobStatus:
            Type: Choice
            Choices:
              - Variable: "$.TranscriptionJob.TranscriptionJobStatus"
                StringEquals: COMPLETED
                Next: Succeeded
              - Variable: "$.TranscriptionJob.TranscriptionJobStatus"
                StringEquals: FAILED
                Next: Failed
            Default: Wait
          Failed:
            Type: Fail
            Cause: 'transcription job failed'
            Error: FAILED
          Succeeded:
            Type: Succeed
      Policies:
        - S3ReadPolicy: {"BucketName": !Ref TranscribeMediaBucket}
        - S3ReadPolicy: {"BucketName": !Ref TranscribeResultsBucket}
        - S3WritePolicy: {"BucketName": !Ref TranscribeResultsBucket}
        - CloudWatchPutMetricPolicy: {}
        - Version: "2012-10-17"
          Statement:
            - Sid: XrayAccessPolicy
              Effect: Allow
              Action:
                - xray:PutTraceSegments
                - xray:PutTelemetryRecords
                - xray:GetSamplingRules
                - xray:GetSamplingTargets
                - xray:GetSamplingStatisticSummaries
              Resource: '*'
            - Sid: TranscribeJobPolicy
              Effect: Allow
              Action:
                - transcribe:GetTranscriptionJob
                - transcribe:StartTranscriptionJob
              Resource: '*'

  MyLLMAppBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'my-llm-apprunner-build-role'
      Path: '/'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  MyLLMAppInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'my-llm-apprunner-role'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: sagemaker-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AllowSageMakerInvoke
                Effect: Allow
                Action:
                  - sagemaker:InvokeEndpoint
                Resource: !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint/*"

  OpenSearchDomainCredentials:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: OpenSearchDomainSecret
      Description: "This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "llm-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'

  OpenSearchServiceDomain:
    DependsOn:
      - OpenSearchDomainCredentials
    Type: AWS::OpenSearchService::Domain
    Properties:
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*/*
      EngineVersion: 'OpenSearch_2.5'
      ClusterConfig:
        InstanceType: "r6g.xlarge.search"
      EBSOptions:
        EBSEnabled: True
        VolumeSize: 20
        VolumeType: 'gp3'
      AdvancedSecurityOptions:
        AnonymousAuthEnabled: False
        Enabled: True
        InternalUserDatabaseEnabled: True
        MasterUserOptions:
          MasterUserName: '{{resolve:secretsmanager:OpenSearchDomainSecret:SecretString:username}}'
          MasterUserPassword: '{{resolve:secretsmanager:OpenSearchDomainSecret:SecretString:password}}'
      NodeToNodeEncryptionOptions:
        Enabled: True
      EncryptionAtRestOptions:
        Enabled: True
        KmsKeyId: alias/aws/es
      DomainEndpointOptions:
        EnforceHTTPS: True

  MyLLMAppRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: 'llm-app-repo'
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt MyLLMAppBuildRole.Arn
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload

# SageMaker stuff below
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LLMAppsBlogIAMRole
      Policies:
        - PolicyName: CustomNotebookAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: ReadFromOpenSearch
                Effect: Allow
                Action:
                  - "es:ESHttp*"
                Resource:
                  - !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*
              - Sid: ReadSecretFromSecretsManager
                Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*"
              - Sid: ReadWriteFromECR
                Effect: Allow
                Action:
                  - "ecr:BatchGetImage"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:DescribeImages"
                  - "ecr:DescribeRepositories"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:ListImages"
                  - "ecr:PutImage"
                  - "ecr:UploadLayerPart"
                  - "ecr:CreateRepository"
                  - "ecr:GetAuthorizationToken"
                  - "ec2:DescribeAvailabilityZones"
                Resource: "*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        - arn:aws:iam::aws:policy/TranslateReadOnly
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  LLMEndpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointName: !Sub
        - '${AppName}-flan-t5-xxl-endpoint-${RandomGUID}'
        - { RandomGUID: !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId ]]]] }
      EndpointConfigName: !GetAtt LLMEndpointConfig.EndpointConfigName

  LLMEndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      EndpointConfigName: !Sub
        - '${AppName}-flan-t5-xxl-endpoint-${RandomGUID}'
        - { RandomGUID: !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId ]]]] }
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: "ml.g5.12xlarge"
          ModelName: !GetAtt LLMModel.ModelName
          VariantName: !GetAtt LLMModel.ModelName
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W1200
            reason: Solution does not have KMS encryption enabled by default

  LLMModel:
    Type: "AWS::SageMaker::Model"
    Properties:
      ModelName: !Sub
        - '${AppName}-flan-t5-xxl-model-${RandomGUID}'
        - { RandomGUID: !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId ]]]] }
      PrimaryContainer:
        ModelDataUrl: !Sub "s3://jumpstart-cache-prod-${AWS::Region}/huggingface-infer/prepack/v1.0.1/infer-prepack-huggingface-text2text-flan-t5-xxl.tar.gz"
        Image: !Sub "763104351884.dkr.ecr.${AWS::Region}.amazonaws.com/pytorch-inference:1.12.0-gpu-py38"
        Environment: {"TS_DEFAULT_WORKERS_PER_MODEL": "1"}
        Mode: "SingleModel"
      ExecutionRoleArn: !GetAtt Role.Arn

  EmbeddingEndpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointName: !Sub
        - '${AppName}-gpt-j-6b-endpoint-${RandomGUID}'
        - { RandomGUID: !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId ]]]] }
      EndpointConfigName: !GetAtt EmbeddingEndpointConfig.EndpointConfigName

  EmbeddingEndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      EndpointConfigName: !Sub
        - '${AppName}-gpt-j-6b-endppoint-${RandomGUID}'
        - { RandomGUID: !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId ]]]] }
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: "ml.g5.2xlarge"
          ModelName: !GetAtt EmbeddingModel.ModelName
          VariantName: !GetAtt EmbeddingModel.ModelName
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W1200
            reason: Solution does not have KMS encryption enabled by default

  EmbeddingModel:
    Type: "AWS::SageMaker::Model"
    Properties:
      ModelName: !Sub
        - '${AppName}-gpt-j-6b-model-${RandomGUID}'
        - { RandomGUID: !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId ]]]] }
      PrimaryContainer:
        ModelDataUrl: !Sub "s3://jumpstart-cache-prod-${AWS::Region}/huggingface-infer/prepack/v1.0.0/infer-prepack-huggingface-textembedding-gpt-j-6b.tar.gz"
        Image: !Sub "763104351884.dkr.ecr.${AWS::Region}.amazonaws.com/pytorch-inference:1.12.0-gpu-py38"
        Environment: {"TS_DEFAULT_WORKERS_PER_MODEL": "2"}
        Mode: "SingleModel"
      ExecutionRoleArn: !GetAtt Role.Arn

Outputs:
  TranscribeMediaBucket:
    Value: !Ref TranscribeMediaBucket
    Description: 'bucket to store media inputs'

  TranscribeResultsBucket:
    Value: !Ref TranscribeResultsBucket
    Description: 'Buckets to store transcribe outputs'

  LLMAppEcrRepo:
    Value: !Sub "${MyLLMAppRepository.RepositoryUri}:latest"
    Description: 'ECR Repo to host docker images'

  OpenSearchDomainEndpoint:
    Description: OpenSearch domain endpoint
    Value:
      'Fn::GetAtt':
        - OpenSearchServiceDomain
        - DomainEndpoint
